In [1]:
import os
import sys
import numpy as np
import torch
import torch.nn as nn

/home/warrior/miniconda3/envs/dl/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [9]:
target = torch.ones([10, 64], dtype=torch.float32)  # 64 classes, batch size = 10
output = torch.full([10, 64], 1.5)  # A prediction (logit)
#pos_weight = torch.ones([64])  # All weights are equal to 1

In [10]:
criterion = torch.nn.BCEWithLogitsLoss()
criterion(output, target)  # -log(sigmoid(1.5))

tensor(0.2014)

## Target with class inidces

In [11]:
pred = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)

In [12]:
pred

tensor([[-2.1933,  0.2501, -0.5174,  0.7760, -1.6690],
        [-0.6522, -2.2804, -0.2807,  0.0362, -0.4162],
        [ 0.1861,  1.2671, -1.8653,  1.6105,  1.8554]], requires_grad=True)

In [13]:
target

tensor([0, 0, 0])

In [14]:
criterion = nn.CrossEntropyLoss()
criterion(pred, target)

tensor(2.6818, grad_fn=<NllLossBackward0>)

# Target with class probabilities

In [15]:
pred = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5).softmax(dim=1)

In [16]:
pred

tensor([[ 1.2411, -1.0458, -0.5736,  0.1482,  0.6596],
        [-0.1103,  0.5884, -1.2385, -0.6841, -1.6410],
        [-0.5560,  2.2213, -0.5620,  0.3255, -0.1131]], requires_grad=True)

In [17]:
target

tensor([[0.5837, 0.1384, 0.1828, 0.0226, 0.0725],
        [0.1382, 0.0240, 0.2921, 0.1535, 0.3922],
        [0.0798, 0.1080, 0.1165, 0.2095, 0.4862]])

In [18]:
criterion = nn.CrossEntropyLoss()
criterion(pred, target)

tensor(2.0980, grad_fn=<DivBackward1>)

## Softmax

In [19]:
m = nn.Softmax(dim=1)
inp = torch.randn(2, 3)

In [21]:
inp

tensor([[ 2.7924, -0.5482,  0.1402],
        [ 0.7060,  0.7959,  0.2153]])

In [22]:
output = m(inp)

In [23]:
output

tensor([[0.9042, 0.0320, 0.0637],
        [0.3695, 0.4043, 0.2262]])